default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: flixtera_development

test:
  <<: *default
  database: flixtera_test

production:
  <<: *default
  database: flixtera_production
  # username: flixtera
  # password: <%= ENV['FLIXTERA_DATABASE_PASSWORD'] %>
